const os = require("node:os");
console.log("Info del SO");
console.log("-----------------");
console.log("Nombre del SO", os.platform());
console.log("Versión del SO", os.version());
console.log("Arquitectura del SO", os.arch());
console.log("CPUS:", os.cpus());
console.log("Memoria libre", os.freemem() / 1024 / 1024);
console.log("Memoria total", os.totalmem() / 1024 / 1024);
console.log("uptime", os.uptime() / 60 / 60);
